export const HELLO_PIC =
  'AgACAgIAAxkBAAIIEmifL8n-oKkQBcWRd93bCCxZzjbwAAJA9TEbI8j4SEpWg-jsFhpsAQADAgADeQADNgQ';

export const HELLO_VIDEO =
  'BAACAgIAAxkBAAIIFWifNEteNHHcaoSdm0lyMclJT-8CAAI5fAACI8j4SH5UHy7jnvXaNgQ';
export const REG_SUCSESS_VIDEO =
  'BAACAgIAAxkBAAIIF2ifNPjat3G4K5RTl1K1fiZ3Hm3uAAJOfAACI8j4SGpv-oSQWIlhNgQ';

export const SAD_FACE_VIDEO =
  'BAACAgIAAxkBAAILH2ijNejePXY4Mqtp0ZH98IYGMHzUAAJ5gAACiGUZSUmi9HqPjCWqNgQ';
export const THAMB_UP_ONE_VIDEO =
  'BAACAgIAAxkBAAILIWijNgcL8yn38SETB1ayRRCYd0LaAAJ9gAACiGUZSbT0YVEfLdVFNgQ';
export const THAMB_UP_TWO_VIDEO =
  'BAACAgIAAxkBAAILJGijNjUP6-qbM5Filc4VK1s4SHLOAAKCgAACiGUZSa-VyuYjTojXNgQ';
export const APPLAUSE_VIDEO =
  'BAACAgIAAxkBAAILLGijNlgWwRKNXS013HBBrPb4t4MbAAKFgAACiGUZSScjTIPSSJQ-NgQ';
